server:
  port: 8000
spring:
  application:
    name: microservice-discovery-eureka-ha
## eureka ： 主要配置属性在EurekaInstanceConfigBean和EurekaClientConfigBean中
eureka:
  instance:
    hostname: spring-cloud-eureka
    # 心跳间隔
    lease-renewal-interval-in-seconds: 3
    # 服务失效时间： 如果多久没有收到请求，则可以删除服务
    lease-expiration-duration-in-seconds: 7
    # 使用IP注册
    # prefer-ip-address: true
  client:
    # 注册自身到eureka服务器
    register-with-eureka: false
    # 表示是否从eureka服务器获取注册信息
    fetch-registry: false
    # 客户端从Eureka Server集群里更新Eureka Server信息的频率
    eureka-service-url-poll-interval-seconds: 60
    # 定义从注册中心获取实例注册服务的信息
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8000/eureka/
      # 设置eureka服务器所在的地址，可以同时向多个服务注册服务
      # defaultZone: http://192.168.21.3:10761/eureka/,http://192.168.21.4:10761/eureka/
  server:
    # renewal-percent-threshold: 0.1
    # 关闭自我保护模式
    enable-self-preservation: false
    # Eureka Server 自我保护系数，当enable-self-preservation=true时，启作用
    # renewal-percent-threshold:
    # 设置清理间隔,单位为毫秒,默认为0
    eviction-interval-timer-in-ms: 3000
    # 设置如果Eureka Server启动时无法从临近Eureka Server节点获取注册信息，它多久不对外提供注册服务
    wait-time-in-ms-when-sync-empty: 6000000
    # 集群之间相互更新节点信息的时间频率
    peer-eureka-nodes-update-interval-ms: 60000